amazonProperties:
    endpointUrl: https://projects33381.s3.amazonaws.com
    accessKey:
    secretKey:
    bucketName: projects33381
    region: us-east-1

spring:
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB